schools/config/routes.rb
Rails.application.routes.draw do
  get 'schools/index'
  
  get 'schools/about'
  
  get 'schools/learn_school_choice_process'

  get 'schools/navigate_school_choice'

  get 'schools/find_feeder_pattern'

  get 'schools/find_school'

  get 'schools/index'
  
  root 'schools#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

schools/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

schools/app/models/location.rb
require 'geocoder'

class Location

	attr_accessor :address
	attr_accessor :latitude
	attr_accessor :longitude
	attr_accessor :coordinates
	
	def initialize(address)
		@address = address
		@coordinates = Geocoder.coordinates(@address)
		if (@coordinates != nil)
			@latitude = @coordinates.first
			@longitude = @coordinates.last
		end
	end
end

schools/app/models/school.rb
require 'soda/client'

class School 
	
	def self.for
		client = SODA::Client.new({:domain => "data.delaware.gov"})
		client.get("https://data.delaware.gov/resource/f6a3-crpj.json", {})  
	end
end

schools/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

schools/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
  def learn_school_choice_process
  end

  def navigate_school_choice
  end

  def find_feeder_pattern
  end

  def find_school
  end
end

schools/app/controllers/schools_controller.rb
require 'geocoder'

class SchoolsController < ApplicationController
  def index
	@schools = School.for
  end

  def about
  end
  
  def learn_school_choice_process
  end

  def navigate_school_choice
  end

  def find_feeder_pattern
	@address = params[:address]
	@coordinates = Geocoder.coordinates(params[:address])
	@locations = Array.new(1, Location.new(@address))
	@hash = Gmaps4rails.build_markers(@locations) do |location, marker|
		marker.lat location.latitude
		marker.lng location.longitude
	end
  end

  def find_school
  end
  
end

schools/app/helpers/application_helper.rb
module ApplicationHelper
end

schools/app/helpers/home_helper.rb
module HomeHelper
end

schools/app/helpers/schools_helper.rb
module SchoolsHelper
end

schools/app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

schools/app/views/home/find_feeder_pattern.html.erb
<h1>Home#find_feeder_pattern</h1>
<p>Find me in app/views/home/find_feeder_pattern.html.erb</p>
<%= form_tag({controller: "schools", action: "find_feeder_pattern"}, method: "get") do %>
  <%= label_tag(:address, "Search for:") %>
  <%= text_field_tag(:address) %>
  <%= submit_tag("Search") %>
<% end %>

schools/app/views/home/find_school.html.erb
<h1>Home#find_school</h1>
<p>Find me in app/views/home/find_school.html.erb</p>

schools/app/views/home/index.html.erb
<p>School choice application are currently open!  To learn more about the school choice process, <%= link_to 'GO HERE', home_learn_school_choice_process_path %>!</p>
<h1>We're here to help you navigate the Delaware School Choice Process.</h1>
<h2><%= link_to 'Navigate School Choice', home_navigate_school_choice_path %></h2>
<h2><%= link_to 'Find Your Feeder Pattern', home_find_feeder_pattern_path %></h2>
<h2><%= link_to 'Find a School', home_find_school_path %></h2>

schools/app/views/home/learn_school_choice_process.html.erb
<h1>Home#learn_school_choice_process</h1>
<p>Find me in app/views/home/learn_school_choice_process.html.erb</p>

schools/app/views/home/navigate_school_choice.html.erb
<h1>Home#navigate_school_choice</h1>
<p>Find me in app/views/home/navigate_school_choice.html.erb</p>

schools/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delaware School Choice Sherpa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<h1><%= link_to 'Delaware School Choice Sherpa', schools_index_path %></h1>
	<%= link_to 'About', schools_about_path %>
	<%= link_to 'Navigate School Choice', schools_navigate_school_choice_path %>
	<%= link_to 'Find Your Feeder Pattern', schools_find_feeder_pattern_path %>
	<%= link_to 'Find a School', schools_find_school_path %>
    <%= yield %>
  </body>
</html>

schools/app/views/schools/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

schools/app/views/schools/find_feeder_pattern.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDVuK_12um_9jpLl2OULssrPVSTAy2B4cI"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<h1>Find Your Feeder School Pattern</h1>
<%= form_tag({controller: "schools", action: "find_feeder_pattern"}, method: "get") do %>
  <%= label_tag(:address, "Search for:") %>
  <%= text_field_tag(:address) %>
  <%= submit_tag("Search") %>
<% end %>
<p><%= content_tag(:span, "#{@address}") %></p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<%= javascript_include_tag "gmaps_google.js", "underscore.js" %>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

schools/app/views/schools/find_school.html.erb
<h1>Home#find_school</h1>
<p>Find me in app/views/home/find_school.html.erb</p>

schools/app/views/schools/get_coordinate.html.erb
<%= content_tag(:span, "#{@address}") %>
	

schools/app/views/schools/index.html.erb
<p>School choice application are currently open!  To learn more about the school choice process, <%= link_to 'GO HERE', schools_learn_school_choice_process_path %>!</p>
<h1>We're here to help you navigate the Delaware School Choice Process.</h1>
<h2><%= link_to 'Navigate School Choice', schools_navigate_school_choice_path %></h2>
<h2><%= link_to 'Find Your Feeder Pattern', schools_find_feeder_pattern_path %></h2>
<h2><%= link_to 'Find a School', schools_find_school_path %></h2>

schools/app/views/schools/learn_school_choice_process.html.erb
<h1>Home#learn_school_choice_process</h1>
<p>Find me in app/views/home/learn_school_choice_process.html.erb</p>

schools/app/views/schools/navigate_school_choice.html.erb
<h1>Home#navigate_school_choice</h1>
<p>Find me in app/views/home/navigate_school_choice.html.erb</p>